-- Run this in Supabase SQL Editor before deploying the Vercel app.

create table if not exists public.user_roles (
  email text not null,
  role text not null check (role in ('admin', 'doctor', 'receptionist')),
  created_at timestamptz not null default now(),
  primary key (email, role)
);

create table if not exists public.settings (
  setting_key text primary key,
  setting_value text
);

create table if not exists public.patients (
  patient_id bigint generated by default as identity primary key,
  patient_number text default '',
  first_name text not null,
  last_name text not null,
  dob date not null,
  gender text not null default '',
  phone text not null default '',
  address text,
  registered_date date not null default current_date,
  nic text default '',
  age integer default 0
);

create table if not exists public.queue (
  queue_id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(patient_id) on delete cascade,
  queue_number integer not null,
  queue_date date not null default current_date,
  status text not null default 'waiting' check (status in ('waiting', 'with_doctor', 'completed')),
  created_at timestamptz not null default now()
);

create table if not exists public.visits (
  visit_id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(patient_id) on delete cascade,
  queue_id bigint references public.queue(queue_id) on delete set null,
  visit_date_time timestamptz not null default now(),
  complaint text default '',
  examination text default '',
  investigation text default '',
  diagnosis text default '',
  treatment text default '',
  referals text default '',
  notes text default '',
  visit_fee numeric(10,2) not null default 0,
  total_bill numeric(10,2) not null default 0,
  is_paid boolean not null default false
);

create table if not exists public.drugs (
  drug_id bigint generated by default as identity primary key,
  drug_name text not null,
  dose text default '',
  batch_number text default '',
  quantity integer not null default 0,
  unit_price numeric(10,2) not null default 0
);

create table if not exists public.visit_drugs (
  visit_drug_id bigint generated by default as identity primary key,
  visit_id bigint not null references public.visits(visit_id) on delete cascade,
  drug_id bigint references public.drugs(drug_id) on delete set null,
  drug_name text default '',
  quantity integer not null default 0,
  total_cost numeric(10,2) not null default 0,
  frequency text default '',
  dose text default '',
  duration text default ''
);

create index if not exists patients_last_name_idx on public.patients(last_name);
create index if not exists patients_phone_idx on public.patients(phone);
create index if not exists patients_nic_idx on public.patients(nic);
create index if not exists queue_date_idx on public.queue(queue_date);
create index if not exists queue_status_idx on public.queue(status);
create index if not exists visits_patient_idx on public.visits(patient_id);
create index if not exists visit_drugs_visit_idx on public.visit_drugs(visit_id);

insert into public.settings (setting_key, setting_value) values
  ('clinic_name', 'Royal Channel Center'),
  ('doctor_name', 'Dr. John Doe, MBBS'),
  ('clinic_address', '123 Health Street, Cityville'),
  ('clinic_phone', 'Tel: +1 234 567 890'),
  ('visit_fee', '500'),
  ('print_page_size', 'A4'),
  ('print_text_size', '14px')
on conflict (setting_key) do nothing;

create or replace function public.is_approved_user()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.user_roles
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

create or replace function public.get_today_queue()
returns table (
  queue_id bigint,
  queue_number integer,
  status text,
  patient_id bigint,
  first_name text,
  last_name text,
  gender text,
  dob date,
  previous_visits bigint,
  visit_id bigint,
  total_bill numeric,
  visit_fee numeric,
  is_paid boolean
)
language sql
stable
as $$
  select
    q.queue_id,
    q.queue_number,
    q.status,
    p.patient_id,
    p.first_name,
    p.last_name,
    p.gender,
    p.dob,
    (
      select count(*)
      from public.visits old_v
      where old_v.patient_id = q.patient_id
        and old_v.visit_date_time::date < current_date
    ) as previous_visits,
    v.visit_id,
    v.total_bill,
    v.visit_fee,
    coalesce(v.is_paid, false) as is_paid
  from public.queue q
  join public.patients p on p.patient_id = q.patient_id
  left join lateral (
    select *
    from public.visits latest_v
    where latest_v.queue_id = q.queue_id
    order by latest_v.visit_id desc
    limit 1
  ) v on true
  where q.queue_date = current_date
  order by
    case q.status when 'waiting' then 1 when 'with_doctor' then 2 else 3 end,
    coalesce(v.is_paid, false),
    q.queue_number;
$$;

alter table public.user_roles enable row level security;
alter table public.settings enable row level security;
alter table public.patients enable row level security;
alter table public.queue enable row level security;
alter table public.visits enable row level security;
alter table public.drugs enable row level security;
alter table public.visit_drugs enable row level security;

drop policy if exists "approved users read settings" on public.settings;
create policy "approved users read settings" on public.settings for select using (public.is_approved_user());

drop policy if exists "users read own roles" on public.user_roles;
create policy "users read own roles" on public.user_roles for select using (lower(email) = lower(auth.jwt() ->> 'email'));

drop policy if exists "approved users read patients" on public.patients;
create policy "approved users read patients" on public.patients for select using (public.is_approved_user());

drop policy if exists "approved users read queue" on public.queue;
create policy "approved users read queue" on public.queue for select using (public.is_approved_user());

drop policy if exists "approved users read visits" on public.visits;
create policy "approved users read visits" on public.visits for select using (public.is_approved_user());

drop policy if exists "approved users read drugs" on public.drugs;
create policy "approved users read drugs" on public.drugs for select using (public.is_approved_user());

drop policy if exists "approved users read visit drugs" on public.visit_drugs;
create policy "approved users read visit drugs" on public.visit_drugs for select using (public.is_approved_user());

do $$
begin
  alter publication supabase_realtime add table public.queue;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.visits;
exception
  when duplicate_object then null;
end $$;

-- Replace these with real clinic Google accounts after enabling Google Auth.
-- insert into public.user_roles (email, role) values
--   ('admin@example.com', 'admin'),
--   ('doctor@example.com', 'doctor'),
--   ('reception@example.com', 'receptionist')
-- on conflict do nothing;
