import { ClinicShell } from "@/components/ClinicShell";
import { requireRole } from "@/lib/auth";

export default async function AdminImport() {
  const { email } = await requireRole(["admin"]);
  return (
    <ClinicShell role="admin" email={email}>
      <div className="mx-auto max-w-3xl">
        <div className="mb-8 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <h2 className="text-2xl font-black text-gray-900 sm:text-3xl">Import Database Backup</h2>
          <a href="/admin/dashboard" className="rounded bg-gray-200 px-4 py-3 text-center font-black text-gray-700">Back</a>
        </div>
        <section className="rounded-xl border-t-4 border-blue-500 bg-white p-4 shadow-sm sm:p-8">
          <p className="mb-6 font-semibold text-gray-600">Upload a .sql backup file that was previously generated by the system. In the online version, paste the converted SQL into Supabase SQL Editor.</p>
          <div className="mb-6 rounded-lg border-2 border-dashed border-gray-300 p-5 text-center sm:p-10">
            <p className="mb-4 text-lg font-black text-blue-600">Click to Browse</p>
            <input type="file" accept=".sql" className="mx-auto block" />
          </div>
          <button className="w-full rounded-lg bg-blue-600 px-6 py-4 text-center text-lg font-black text-white shadow">Start Recovery Process</button>
          <p className="mt-6 text-center text-sm font-bold text-red-500">Warning: Restoring data may affect currently running operations.</p>
        </section>
      </div>
    </ClinicShell>
  );
}
