<?php
session_start();
if (!isset($_SESSION['admin_logged_in'])) {
    header('Location: login.php');
    exit;
}
require_once '../config/db.php';

$msg = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_FILES['backup_file'])) {
    $file = $_FILES['backup_file'];
    if ($file['error'] === UPLOAD_ERR_OK) {
        $sql = file_get_contents($file['tmp_name']);
        try {
            $pdo->exec($sql);
            $msg = "<div class='bg-emerald-500/20 border-l-4 border-emerald-500/50 text-emerald-300 p-4 rounded-xl mb-6 font-bold shadow-sm backdrop-blur-sm'>Database imported successfully!</div>";
        } catch (Exception $e) {
            $msg = "<div class='bg-rose-500/20 border-l-4 border-rose-500/50 text-rose-300 p-4 rounded-xl mb-6 font-bold shadow-sm backdrop-blur-sm'>Import Error: " . htmlspecialchars($e->getMessage()) . "</div>";
        }
    } else {
        $msg = "<div class='bg-rose-500/20 border-l-4 border-rose-500/50 text-rose-300 p-4 rounded-xl mb-6 font-bold shadow-sm backdrop-blur-sm'>Upload error.</div>";
    }
}
?>
<?php
$pageTitle = 'Import Database - Admin';
include '../includes/header.php';
?>
<body class="bg-[conic-gradient(at_bottom_right,_var(--tw-gradient-stops))] flex h-screen overflow-hidden from-slate-900 via-slate-800 to-zinc-900 text-slate-200 font-sans">
    <!-- Sidebar -->
    <?php include '../includes/sidebar_admin.php'; ?>

    <div class="flex-1 overflow-y-auto relative z-0">
        <!-- Mobile Nav Header -->
        <nav class="bg-white/5 backdrop-blur-xl border-b border-white/10 text-white p-4 shadow-lg flex justify-between items-center z-10 relative md:hidden">
            <h1 class="text-xl font-bold tracking-tight drop-shadow-md">Admin Panel</h1>
            <a href="dashboard.php" class="px-3 py-1.5 bg-white/5 hover:bg-white/10 border border-white/10 text-slate-200 shadow-sm transition-all text-sm font-bold rounded-lg">Menu</a>
        </nav>
        
        <main class="p-8 max-w-3xl mx-auto relative z-0">
            <div class="flex items-center justify-between mb-8">
                <h2 class="text-3xl font-bold text-white tracking-tight drop-shadow-md">Import Database Backup</h2>
                <a href="dashboard.php" class="px-4 py-2 bg-white/5 hover:bg-white/10 border border-white/10 text-slate-200 shadow-sm transition-all text-sm font-bold rounded-lg">Back</a>
            </div>

            <?= $msg ?>
            
            <div class="bg-white/5 backdrop-blur-3xl p-8 rounded-[2rem] shadow-2xl border border-white/10 border-t-indigo-500/50">
                <p class="text-slate-300 mb-6 font-medium">Upload a `.sql` backup file that was previously generated by the system. This will restore missing records and update existing records.</p>
                
                <form method="POST" enctype="multipart/form-data" class="space-y-6">
                    <div class="border-2 border-dashed border-white/20 rounded-xl p-10 text-center hover:bg-white/5 hover:border-white/30 transition-all cursor-pointer backdrop-blur-sm group">
                        <label class="block cursor-pointer">
                            <span class="sr-only">Choose backup file</span>
                            <div class="text-indigo-400 font-bold text-lg mb-2 group-hover:text-indigo-300 transition-colors drop-shadow-sm">Click to Browse</div>
                            <input type="file" name="backup_file" accept=".sql" required class="block w-full text-sm text-slate-400
                                file:mr-4 file:py-2 file:px-4
                                file:rounded-xl file:border file:border-indigo-500/30
                                file:text-sm file:font-semibold
                                file:bg-indigo-500/20 file:text-indigo-300
                                hover:file:bg-indigo-500/30 cursor-pointer
                                file:transition-all
                            "/>
                        </label>
                    </div>
                    
                    <button type="submit" class="w-full bg-indigo-500/20 text-indigo-200 border border-indigo-500/30 py-3.5 rounded-xl font-bold hover:bg-indigo-500/30 hover:shadow-[0_0_20px_rgba(99,102,241,0.4)] transition-all text-lg shadow-sm backdrop-blur-md">
                        Start Recovery Process
                    </button>
                    <p class="text-center text-xs text-rose-400 mt-2 font-bold drop-shadow-sm">Warning: Restoring data may affect currently running operations.</p>
                </form>
            </div>
        </main>
    </div>
</body>
</html>
