<?php
session_start();
if (!isset($_SESSION['admin_logged_in'])) {
    header('Location: login.php');
    exit;
}
require_once '../config/db.php';

$msg = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_FILES['backup_file'])) {
    $file = $_FILES['backup_file'];
    if ($file['error'] === UPLOAD_ERR_OK) {
        $sql = file_get_contents($file['tmp_name']);
        try {
            $pdo->exec($sql);
            $msg = "<div class='bg-green-100 border-l-4 border-green-500 text-green-800 p-4 rounded mb-6 font-bold'>Database imported successfully!</div>";
        } catch (Exception $e) {
            $msg = "<div class='bg-red-100 border-l-4 border-red-500 text-red-800 p-4 rounded mb-6 font-bold'>Import Error: " . htmlspecialchars($e->getMessage()) . "</div>";
        }
    } else {
        $msg = "<div class='bg-red-100 border-l-4 border-red-500 text-red-800 p-4 rounded mb-6 font-bold'>Upload error.</div>";
    }
}
?>
<?php
$pageTitle = 'Import Database - Admin';
include '../includes/header.php';
?>
<body class="bg-gray-50 flex h-screen overflow-hidden">
    <!-- Sidebar -->
    <?php include '../includes/sidebar_admin.php'; ?>

    <div class="flex-1 overflow-y-auto">
        <!-- Mobile Nav Header -->
        <nav class="bg-gray-900 text-white p-4 md:hidden flex justify-between items-center shadow-md">
            <h1 class="text-xl font-bold">Admin Panel</h1>
            <a href="dashboard.php" class="px-3 py-1 bg-gray-700 rounded">Menu</a>
        </nav>
        
        <main class="p-8 max-w-3xl mx-auto">
            <div class="flex items-center justify-between mb-8">
                <h2 class="text-3xl font-bold text-gray-800">Import Database Backup</h2>
                <a href="dashboard.php" class="px-4 py-2 bg-gray-200 hover:bg-gray-300 text-gray-800 rounded font-semibold transition">Back</a>
            </div>

            <?= $msg ?>
            
            <div class="bg-white p-8 rounded-xl shadow border-t-4 border-blue-500">
                <p class="text-gray-600 mb-6">Upload a `.sql` backup file that was previously generated by the system. This will restore missing records and update existing records.</p>
                
                <form method="POST" enctype="multipart/form-data" class="space-y-6">
                    <div class="border-2 border-dashed border-gray-300 rounded-lg p-10 text-center hover:bg-gray-50 transition">
                        <label class="block cursor-pointer">
                            <span class="sr-only">Choose backup file</span>
                            <div class="text-blue-600 font-bold text-lg mb-2">Click to Browse</div>
                            <input type="file" name="backup_file" accept=".sql" required class="block w-full text-sm text-gray-500
                                file:mr-4 file:py-2 file:px-4
                                file:rounded-full file:border-0
                                file:text-sm file:font-semibold
                                file:bg-blue-50 file:text-blue-700
                                hover:file:bg-blue-100 cursor-pointer
                            "/>
                        </label>
                    </div>
                    
                    <button type="submit" class="w-full bg-blue-600 text-white py-3 rounded-lg font-bold hover:bg-blue-700 transition text-lg shadow-md">
                        Start Recovery Process
                    </button>
                    <p class="text-center text-xs text-red-500 mt-2 font-bold">Warning: Restoring data may affect currently running operations.</p>
                </form>
            </div>
        </main>
    </div>
</body>
</html>
